export const ORDERS_CONNECTION_START: 'ORDERS_CONNECTION_START' = 'ORDERS_CONNECTION_START';
export const ORDERS_CONNECTION_SUCCESS: 'ORDERS_CONNECTION_SUCCESS' = 'ORDERS_CONNECTION_SUCCESS';
export const ORDERS_CONNECTION_ERROR: 'ORDERS_CONNECTION_ERROR' = 'ORDERS_CONNECTION_ERROR';
export const ORDERS_CONNECTION_CLOSED: 'ORDERS_CONNECTION_CLOSED' = 'ORDERS_CONNECTION_CLOSED';
export const ORDERS_CONNECTION_STOP: 'ORDERS_CONNECTION_STOP' = 'ORDERS_CONNECTION_STOP';
export const ORDERS_GET_MESSAGE: 'ORDERS_GET_MESSAGE' = 'ORDERS_GET_MESSAGE';
export const ORDERS_SEND_MESSAGE: 'ORDERS_SEND_MESSAGE' = 'ORDERS_SEND_MESSAGE';